/*
 * arduinoStd.h
 *
 *  Created on: Apr 19, 2018
 *      Author: Pat Deegan
 *
 *  arduinoStd is part of the LM75-derived temperature sensor project.
 *  Copyright (C) 2018 Pat Deegan, psychogenic.com
 *
 *  Released under the same BSD 3-Clause License and terms
 *  as the library.
 *
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 *  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 *  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 *  DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 *  FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 *  DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 *  SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 *  CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 *  OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 *  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 */

#ifndef TEMPERATURE_LM75_DERIVED_SRC_INCLUDES_PLATFORM_ARDUINOSTD_H_
#define TEMPERATURE_LM75_DERIVED_SRC_INCLUDES_PLATFORM_ARDUINOSTD_H_


#include <Wire.h>
#define WireDefault	Wire
namespace LM75 {
typedef TwoWire I2CWire;
}



#endif /* TEMPERATURE_LM75_DERIVED_SRC_INCLUDES_PLATFORM_ARDUINOSTD_H_ */
